- menu_name: "Services"

- name: "Contact"
  url: "/thatslifesci/contact/"
  title: "Contact"

- name: "RSS"
  url: "/thatslifesci/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/thatslifesci/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/thatslifesci/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
